django_sis/urls.py
from django.conf.urls.defaults import *
from ecwsp.sis.views import *
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include("massadmin.urls")),
    (r'^admin_export/', include("admin_export.urls")),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^$', 'ecwsp.sis.views.index'),

    (r'^sis/', include('ecwsp.sis.urls')),
    (r'^admin/jsi18n', 'django.views.i18n.javascript_catalog'),
    
    (r'^accounts/password_change/$', 'django.contrib.auth.views.password_change'),
    (r'^accounts/password_change_done/$', 'django.contrib.auth.views.password_change_done'),
    (r'^logout/$', logout_view),
  #  (r'^chart/$',chart_fte),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
    (r'^admin/', include(admin.site.urls) ),
    
    (r'^ajax_select/', include('ajax_select.urls')),
    (r'^ajax_filtered_fields/', include('ajax_filtered_fields.urls')),
)

if settings.GAPPS:
    urlpatterns += patterns('', (r'^accounts/login/$', 'google_auth.views.login'), )
else:
    urlpatterns += patterns('', (r'^accounts/login/$', 'django.contrib.auth.views.login'), )

if 'ldap_groups' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',(r'^ldap_grp/', include('ldap_groups.urls')),)
if 'admin_advanced_filter' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^admin_advanced_filter/', include('admin_advanced_filter.urls')), )
    
if 'ecwsp.discipline' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^discipline/', include('ecwsp.discipline.urls')), )
if 'ecwsp.attendance' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^attendance/', include('ecwsp.attendance.urls')), )
if 'ecwsp.schedule' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^schedule/', include('ecwsp.schedule.urls')), )
if 'ecwsp.work_study' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^work_study/', include('ecwsp.work_study.urls')), )
if 'ecwsp.admissions' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^admissions/', include('ecwsp.admissions.urls')), )
if 'ecwsp.omr' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^omr/', include('ecwsp.omr.urls')), )
if 'ecwsp.volunteer_track' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^volunteer_track/', include('ecwsp.volunteer_track.urls')), )
if 'ecwsp.benchmark_grade' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^benchmark_grade/', include('ecwsp.benchmark_grade.urls')), )
if 'ecwsp.inventory' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^inventory/', include('ecwsp.inventory.urls')), )
if 'ecwsp.engrade_sync' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^engrade_sync/', include('ecwsp.engrade_sync.urls')), )
if 'ecwsp.grades' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^grades/', include('ecwsp.grades.urls')), )
if 'ecwsp.naviance_sso' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^naviance_sso/', include('ecwsp.naviance_sso.urls')), )
if 'ecwsp.alumni' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^alumni/', include('ecwsp.alumni.urls')), )
if 'ecwsp.integrations.canvas_sync' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^canvas_sync/', include('ecwsp.integrations.canvas_sync.urls')), )
if 'ecwsp.integrations.schoolreach' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^schoolreach/', include('ecwsp.integrations.schoolreach.urls')), )
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )
if 'report_builder' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^report_builder/', include('report_builder.urls')),
if 'simple_import' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^simple_import/', include('simple_import.urls')),
if 'responsive_dashboard' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^', include('responsive_dashboard.urls')),
if 'sentry' in settings.INSTALLED_APPS:    
    urlpatterns += patterns('', (r'^sentry/', include('sentry.web.urls')),)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,})
    )

if settings.CAS:
    urlpatterns += patterns('',
        (r'^accounts/login/$', 'cas.views.login'),
        (r'^accounts/logout/$', 'cas.views.logout'),
    )

def handler500(request):
    """
    500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html') # You need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

ecwsp/volunteer_track/urls.py
from django.conf.urls.defaults import *
from ecwsp.volunteer_track.views import *

urlpatterns = patterns('',
    (r'^volunteer/$', student_dash),
    (r'^volunteer/site$', student_site_approval),
    (r'^volunteer/hours/(?P<id>\d+)/$', student_hours),
    (r'^volunteer/change_supervisor/(?P<id>\d+)/$', change_supervisor),
    (r'^approve$', approve),
)

ecwsp/volunteer_track/models.py
#   Copyright 2011 David M Burke
#   Author Callista Goss <calli@burkesoftware.com>
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#     
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#      
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.


from django.db import models
from django.db.models import Sum
from django.contrib.localflavor.us.models import *
from django.contrib import messages
from django.conf import settings

from datetime import datetime
import random
import sys
import logging

from ecwsp.administration.models import Configuration

class Hours(models.Model):
    volunteer_site = models.ForeignKey('VolunteerSite')
    date = models.DateField(blank = False, null = False, validators=settings.DATE_VALIDATORS)
    hours = models.FloatField()
    time_stamp = models.DateTimeField(auto_now_add=True, validators=settings.DATE_VALIDATORS)
    class Meta:
        verbose_name = "Hours"
        verbose_name_plural = "Hours"
        unique_together = ("volunteer_site","date")
    def __unicode__(self):
        return unicode(self.hours)

class Site(models.Model):
    site_name = models.CharField(max_length=255, unique=True)
    site_address = models.CharField(max_length=511)
    site_city = models.CharField(max_length=768)
    site_state = models.CharField(max_length=30)
    site_zip = models.CharField(max_length=30)
    def __unicode__(self):
        return unicode(self.site_name)

class SiteSupervisor(models.Model):
    name = models.CharField(max_length=200)
    site = models.ForeignKey('Site',blank=True,null=True)
    phone = PhoneNumberField(max_length=40, blank=True)
    email = models.EmailField(max_length=200, blank=True)
    def __unicode__(self):
        return unicode(self.name)

class VolunteerSite(models.Model):
    inactive = models.BooleanField()
    volunteer = models.ForeignKey('Volunteer')
    site = models.ForeignKey(Site)
    supervisor = models.ForeignKey(SiteSupervisor,blank=True,null=True)
    site_approval = models.CharField(max_length=16, choices=(('Accepted','Accepted'),('Rejected', 'Rejected'),('Submitted', 'Submitted')), blank=True)
    contract = models.BooleanField()
    job_description = models.TextField(blank=True)
    hours_confirmed = models.BooleanField()
    comment = models.TextField(blank=True)
    secret_key = models.CharField(max_length=20, blank=True, editable=False)
    
    def __unicode__(self):
        return '%s at %s' % (self.volunteer,self.site)
    
    def genKey(self):
        key = ''
        alphabet = 'abcdefghijklmnopqrstuvwxyz1234567890_-'
        for x in random.sample(alphabet,random.randint(19,20)):
            key += x
        self.secret_key = key
    
    def save(self, saved_by_volunteer=False, *args, **kwargs):
        if not self.secret_key or self.secret_key == "":
            self.genKey()
        
        if saved_by_volunteer:
            if not self.volunteer.email_queue:
                self.volunteer.email_queue = ""
            self.volunteer.email_queue += "Added Site %s. " % (unicode(self.site))
            self.volunteer.save()
        if self.id:
            old_volunteer = VolunteerSite.objects.get(id=self.id)
            if old_volunteer.site_approval == "Submitted" and self.site_approval == "Accepted":
                try:
                    from django.core.mail import send_mail
                    from_email = Configuration.get_or_default("From Email Address",default="donotreply@change.me").value
                    msg = "Hello %s,\nYour site %s has been approved!" % (self.volunteer, self.site)
                    subject = "Site approval"
                    send_to = self.volunteer.student.get_email
                    send_mail(subject, msg, from_email, [send_to])
                except:
                    exc_type, exc_obj, exc_tb = sys.exc_info()
                    fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
                    logging.warning(
                        'Unable to send email to volunteer about site approval! %s' % (self,),
                        exc_info=True,
                        extra={'request': request,'exception':exc_type,'traceback':'%s %s' % (fname,exc_tb.tb_lineno)}
                        )
        super(VolunteerSite, self).save(*args, **kwargs)
    
    def send_email_approval(self):
        """
        Send email to supervisor for approval
        """
        if not self.site_supervisor or not self.site_supervisor.email:
            return None
        try:
            sendTo = self.site_supervisor.email
            subject = "Volunteer hours approval for " + unicode(self.student)
            msg = "Hello " + unicode(self.site_supervisor.name) + ",\nPlease click on the link below to approve the time sheet\n" + \
                settings.BASE_URL + "/volunteer_tracker/approve?key=" + str(self.secret_key)
            from_addr = Configuration.get_or_default("From Email Address", "donotreply@example.org").value
            send_mail(subject, msg, from_addr, [sendTo])
        except:
            logging.warning("Unable to send email to volunteer's supervisor! %s" % (self,), exc_info=True)
    
    def hours_at_site(self):
        return self.hours_set.all().aggregate(Sum('hours'))['hours__sum']

def get_hours_default():
    return Configuration.get_or_default('Volunteer Track Required Hours', default=20).value
class Volunteer(models.Model):
    student = models.OneToOneField('sis.Student')
    sites = models.ManyToManyField(Site,blank=True,null=True,through='VolunteerSite')
    attended_reflection = models.BooleanField(verbose_name = "Attended")
    hours_required = models.IntegerField(default=get_hours_default, blank=True, null=True)
    notes = models.TextField(blank=True)
    last_updated = models.DateTimeField(default = datetime.now)
    email_queue = models.CharField(default="", max_length=1000, blank=True, editable=False, help_text="Used to store nightly notification emails")
    def __unicode__(self):
        return unicode(self.student)
            
    def hours_completed(self):
        return self.volunteersite_set.all().aggregate(Sum('hours__hours'))['hours__hours__sum']

ecwsp/volunteer_track/forms.py
#   Copyright 2011 David M Burke
#   Author Callista Goss <calli@burkesoftware.com>
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#     
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#      
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.

from django import forms
from ecwsp.volunteer_track.models import *
from ajax_select.fields import AutoCompleteSelectField
from django.forms import HiddenInput, ChoiceField
from django.contrib.admin import widgets as adminwidgets

class inputTimeForm(forms.ModelForm):
    class Meta:
        model = Hours
        widgets = {
            'date':adminwidgets.AdminDateWidget(),
            'volunteer_site':forms.HiddenInput(),
            }
        
class NewSiteForm(forms.ModelForm):
    class Meta:
        model = Site
    job_description = forms.CharField(widget=forms.Textarea(attrs={'rows':3}), required=True)

class ExistingSiteForm(forms.ModelForm):
    class Meta:
        model = VolunteerSite
        fields = ['site','job_description']
        widgets = {'job_description':forms.Textarea(attrs={'rows':3})}
        
class SupervisorForm(forms.ModelForm):
    class Meta:
        model = SiteSupervisor
        exclude = ['site']
    
class SelectSupervisorForm(forms.Form):    
    select_existing = forms.ModelChoiceField(SiteSupervisor.objects.all(), required=False)
    

ecwsp/volunteer_track/templates/volunteer_track/approve.html
{% extends "base.html" %}

{% block css %}
	tr.border:nth-child(odd)    { background-color:#eee; }
	tr.border:nth-child(even)    { background-color:#fff; }
	
	table.border{
		width: 100%; 
		margin:auto; 
		border-collapse: collapse;
		border: 3px solid #666666; 
	}
	td.border {
		padding: 2px;
		padding-left: 6px;
		border: 2px solid #666666;
	}
{% endblock %}

{% block content %}
<h2> Approve Volunteer Hours for {{ volunteer_site.volunteer }} </h2>

<table>
    <tr>
        <td>
            Work Site: {{ volunteer_site.site }} <br/>
            Supervisor: {{ volunteer_site.supervisor }} <br/>
	    Hours Complete at Site: {{ volunteer_site.hours_at_site }} <br/>
            Total Hours Complete: {{ volunteer_site.volunteer.hours_completed }} <br/>
            Hours Required: {{ volunteer_site.volunteer.hours_required }} <br/>
        </td>
        <td style="padding:30px;">
            <table class="border">
                <tr class="border">
                    <th class="border">Date</th>
                    <th class="border">Site</th>
                    <th class="border">Hours</th>
                    <th class="border">Submited</th>
                </tr>
                 {% for hour in volunteer_site.hours_set.all %}
                    <tr class="border">
                        <td class="border">{{ hour.date }}</td>
                        <td class="border">{{ hour.site }}</td>
                        <td class="border" style="text-align: right;">{{ hour.hours }}</td>
                        <td class="border">{{ hour.time_stamp }}</td>
                    </tr>
                {% endfor %}
            </table>
        </td>
    </tr>
</table>

<form method="post">
    <input type="submit" name="approve" value="Click here approve"/> 
</form>
If there is a problem please contact school staff.

{% endblock %}

ecwsp/volunteer_track/templates/volunteer_track/dash.html
{% extends "base.html" %}

{% block head %}
    {{ block.super }}
    <style type="text/css">
        li {
            margin-left: 2em;
        }
    </style>
{% endblock %}

{% block content %}
<h2> Volunteer Dashboard </h2>
<fieldset>
    <legend>Student: {{ student }} </legend>
    Work Site{{ student.volunteersite_set.all.count|pluralize }}:
    <ul> 
        {% for volunteersite in student.volunteersite_set.all %}
            <li>
                {{ volunteersite.site }} ({{ volunteersite.site_approval }}) <br/>
                {{ volunteersite.supervisor }} <a href="{% url "ecwsp.volunteer_track.views.change_supervisor" volunteersite.id %}">Change</a> (Requires approval)<br/>
                {% if not volunteersite.inactive and volunteersite.site_approval == "Accepted" %}
                    <a href="{% url "ecwsp.volunteer_track.views.student_hours" volunteersite.id %}">Log Hours</a><br/>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    Hours Complete: {{ student.hours_completed }} <br/>
    Hours Required: {{ student.hours_required }} <br/>
    </fieldset>
<br/>

<a href="{% url "ecwsp.volunteer_track.views.student_site_approval" %}">Add New Site</a> (Requires approval)

{% endblock %}

ecwsp/volunteer_track/templates/volunteer_track/student_change_supervisor.html
{% extends "base.html" %}

{% block content %}
<h1> Select Supervisor at {{ site }} </h1>
<div class="subhead-text">You may choose an existing supervisor</div>
<form method="post">
    <p>{{ select_supervisor_form }}</p>
    Or add a new one
    <div>
        {{ supervisor_form }}
    </div>
    <input type="submit" class="button gray"/>
</form>
{% endblock %}

ecwsp/volunteer_track/templates/volunteer_track/student_site_approval.html
{% extends "base.html" %}

{% block content %}


<h1>Volunteer (choose an option)</h1>


<div class="volunteer-left">
<div class="subhead-text">
I want to volunteer at an <strong>existing site</strong>.
</div>


<form method="post" class="inline-label">
    <div class="volunteer-field">
		    {{ existing_site_form.site.label }}
		    {{ existing_site_form.site }}
		    {{ existing_site_form.site.errors }}
    </div>
    
    <div class="volunteer-field">
		    <label for="id_job_description" class="login">Job Description</label>
		    <textarea id="id_job_description" name="job_description" class="volunteer-description"></textarea>
    </div>
    
    <div class="clear"></div>
    
    <div class="submitwrap">
	<input type="submit" name="existing_site_submit" class="button gray" value="Submit for Approval">
    </div>
</form>


</div><!-- .LEFT COLUMN -->

<div class="volunteer-right">
<div class="subhead-text">
I want to volunteer at a <strong>new site</strong>.
</div>

<form method="post" action="" class="inline-label">

<div class="volunteer-field">
		<label for="id_{{ new_site_form.site_name.html_name }}" class="login">Site Name</label>
		<input type="text" id="id_{{ new_site_form.site_name.html_name }}" name="{{ new_site_form.site_name.html_name }}" value="{{ new_site_form.site_name.value|default_if_none:"" }}" class="volunteer">
		{{ new_site_form.site_name.errors }}
</div>

<div class="volunteer-field">
		<label for="id_{{ new_site_form.site_address.html_name }}" class="login">Address</label>
		<input type="text" id="id_{{ new_site_form.site_address.html_name }}" name="{{ new_site_form.site_address.html_name }}" value="{{ new_site_form.site_address.value|default_if_none:"" }}" class="volunteer">
		{{ new_site_form.site_address.errors }}
</div>


<div class="volunteer-city">
		<label for="id_{{ new_site_form.site_city.html_name }}" class="login">City</label>
		<input type="text" id="id_{{ new_site_form.site_city.html_name }}" name="{{ new_site_form.site_city.html_name }}" value="{{ new_site_form.site_city.value|default_if_none:"" }}" class="volunteer">
		{{ new_site_form.site_city.errors }}
</div>
<div class="volunteer-state">
		<label for="id_{{ new_site_form.site_state.html_name }}" class="login">State</label>
		<input type="text" id="id_{{ new_site_form.site_state.html_name }}" name="{{ new_site_form.site_state.html_name }}" value="{{ new_site_form.site_state.value|default_if_none:"" }}" class="volunteer">
		{{ new_site_form.site_state.errors }}
</div>
<div class="volunteer-zip">
		<label for="id_{{ new_site_form.site_zip.html_name }}" class="login">Zip</label>
		<input type="text" id="id_{{ new_site_form.site_zip.html_name }}" name="{{ new_site_form.site_zip.html_name }}" value="{{ new_site_form.site_zip.value|default_if_none:"" }}" class="volunteer">
		{{ new_site_form.site_zip.errors }}
</div>


<div class="volunteer-field">
		<label for="id_{{ new_site_form.job_description.html_name }}" class="login">Job Description</label>
		<textarea id="id_{{ new_site_form.job_description.html_name }}" name="{{ new_site_form.job_description.html_name }}" class="volunteer-description">{{ new_site_form.job_description.value|default_if_none:"" }}</textarea>
		{{ new_site_form.job_description.errors }}
</div>

<div class="clear"></div>
<div class="spacer-3"></div>


<div class="volunteer-field">
		<label for="id_{{ supervisor_form.name.html_name }}" class="login">Supervisor Name</label>
		<input type="text" id="id_{{ supervisor_form.name.html_name }}" name="{{ supervisor_form.name.html_name }}" value="{{ supervisor_form.name.value|default_if_none:"" }}" class="volunteer">
		{{ supervisor_form.name.errors }}
</div>

<div class="volunteer-superphone">
		<label for="id_{{ supervisor_form.phone.html_name }}" class="login">Phone</label>
		<input type="text" id="id_{{ supervisor_form.phone.html_name }}" name="{{ supervisor_form.phone.html_name }}" value="{{ supervisor_form.phone.value|default_if_none:"" }}" class="volunteer">
		{{ supervisor_form.phone.errors }}
</div>
<div class="volunteer-superemail">
		<label for="id_{{ supervisor_form.email.html_name }}" class="login">Email</label>
		<input type="text" id="id_{{ supervisor_form.email.html_name }}" name="{{ supervisor_form.email.html_name }}" value="{{ supervisor_form.email.value|default_if_none:"" }}" class="volunteer">
		{{ supervisor_form.email.errors }}
</div>

<div class="clear"></div>

<div class="submitwrap">
<input type="submit" class="button gray" name="new_site_submit" value="Submit New Site for Approval">
</div>

</form>


</div><!-- .RIGHT COLUMN -->


<div class="clear"></div>


<div class="spacer-2"></div>
{% endblock %}

ecwsp/volunteer_track/templates/volunteer_track/student_volunteer_hours.html
{% extends "base.html" %}
{% load admin_static %}{% load url from future %}{% load i18n grp_tags %}


{% block head %}
<script type="text/javascript" src="/static/js/jquery.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui.js"></script>
<script>
	$(function() {
		$(".vDateField").datepicker();
		$("#format" ).change(function() {
			$( "#datepicker" ).datepicker( "option", "dateFormat", $( this ).val() );
		});
	});
</script>
<link rel="stylesheet" href="/static/css/smoothness/jquery-ui.css" type="text/css" />
{% endblock %}

{% block content %}        
    <div class="fixed-width"> 
        <h1>Service Hours Record Sheet</h1>
	<br />
         <p class="instructions"><b><u>INSTRUCTIONS:</u></b> Please fill in all the hours you have completed.
         Note the date and number of hours you completed on that date to the best of your ability.  You DO NOT need to print this form.</p>
         <br/>
        <form action="" name = "volunteer form" onsubmit="" method="post">
            <table style="width:100%;">
                <tr>
                   <td style="width:49%;">
                        <fieldset>
                            <legend>{{ student }}</legend>
                            <p>Service site: {{ volunteer_site.site }}</p> 
                            <p>Supervisor: {{ volunteer_site.supervisor }} </p> 
                            <p>Hours at Site: {{ volunteer_site.hours_at_site }}</p>
                            <p>Total hours completed: {{ student.hours_completed }} </p>
                            <p>Hours required: {{ student.hours_required }} </p> 
                        </fieldset>
                   </td>
                   <td style="width:49%;">
                        <table>
                            {{ form }}
                        </table>
                   </td>
                </tr>
            </table>
            <input class="button" type="submit" value="Click Here to Save Your Work"/>
            
        </form> 
	</div> 

{% endblock %}