django_sis/urls.py
from django.conf.urls.defaults import *
from ecwsp.sis.views import *
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include("massadmin.urls")),
    (r'^admin_export/', include("admin_export.urls")),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^$', 'ecwsp.sis.views.index'),

    (r'^sis/', include('ecwsp.sis.urls')),
    (r'^admin/jsi18n', 'django.views.i18n.javascript_catalog'),
    
    (r'^accounts/password_change/$', 'django.contrib.auth.views.password_change'),
    (r'^accounts/password_change_done/$', 'django.contrib.auth.views.password_change_done'),
    (r'^logout/$', logout_view),
  #  (r'^chart/$',chart_fte),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
    (r'^admin/', include(admin.site.urls) ),
    
    (r'^ajax_select/', include('ajax_select.urls')),
    (r'^ajax_filtered_fields/', include('ajax_filtered_fields.urls')),
)

if settings.GAPPS:
    urlpatterns += patterns('', (r'^accounts/login/$', 'google_auth.views.login'), )
else:
    urlpatterns += patterns('', (r'^accounts/login/$', 'django.contrib.auth.views.login'), )

if 'ldap_groups' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',(r'^ldap_grp/', include('ldap_groups.urls')),)
if 'admin_advanced_filter' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^admin_advanced_filter/', include('admin_advanced_filter.urls')), )
    
if 'ecwsp.discipline' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^discipline/', include('ecwsp.discipline.urls')), )
if 'ecwsp.attendance' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^attendance/', include('ecwsp.attendance.urls')), )
if 'ecwsp.schedule' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^schedule/', include('ecwsp.schedule.urls')), )
if 'ecwsp.work_study' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^work_study/', include('ecwsp.work_study.urls')), )
if 'ecwsp.admissions' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^admissions/', include('ecwsp.admissions.urls')), )
if 'ecwsp.omr' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^omr/', include('ecwsp.omr.urls')), )
if 'ecwsp.volunteer_track' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^volunteer_track/', include('ecwsp.volunteer_track.urls')), )
if 'ecwsp.benchmark_grade' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^benchmark_grade/', include('ecwsp.benchmark_grade.urls')), )
if 'ecwsp.inventory' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^inventory/', include('ecwsp.inventory.urls')), )
if 'ecwsp.engrade_sync' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^engrade_sync/', include('ecwsp.engrade_sync.urls')), )
if 'ecwsp.grades' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^grades/', include('ecwsp.grades.urls')), )
if 'ecwsp.naviance_sso' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^naviance_sso/', include('ecwsp.naviance_sso.urls')), )
if 'ecwsp.alumni' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^alumni/', include('ecwsp.alumni.urls')), )
if 'ecwsp.integrations.canvas_sync' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^canvas_sync/', include('ecwsp.integrations.canvas_sync.urls')), )
if 'ecwsp.integrations.schoolreach' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', (r'^schoolreach/', include('ecwsp.integrations.schoolreach.urls')), )
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )
if 'report_builder' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^report_builder/', include('report_builder.urls')),
if 'simple_import' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^simple_import/', include('simple_import.urls')),
if 'responsive_dashboard' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^', include('responsive_dashboard.urls')),
if 'sentry' in settings.INSTALLED_APPS:    
    urlpatterns += patterns('', (r'^sentry/', include('sentry.web.urls')),)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,})
    )

if settings.CAS:
    urlpatterns += patterns('',
        (r'^accounts/login/$', 'cas.views.login'),
        (r'^accounts/logout/$', 'cas.views.logout'),
    )

def handler500(request):
    """
    500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html') # You need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

ecwsp/work_study/urls.py
from django.conf.urls.defaults import *
from ecwsp.work_study import views

urlpatterns = patterns('',
    (r'^reports/$', views.report_builder_view),
    (r'^student_timesheet/$', views.student_timesheet),
    (r'^supervisor/create_timesheet/(?P<studentId>\d+)/$', views.create_time_card),
    (r'^supervisor/change_supervisor/(?P<studentId>\d+)/$', views.change_supervisor),
    (r'^supervisor/$', views.supervisor_dash),
    (r'^supervisor/view/$', views.supervisor_view),
    (r'^supervisor/view/xls/$', views.supervisor_xls),
    (r'^student/view/$', views.student_view),
    (r'^student/edit/(?P<tsid>\d+)/$', views.student_edit),
    (r'^approve/$', views.approve),
    (r'^supervisor/delete/$', views.timesheet_delete),
    (r'^dol/$',views.dol_form),
    (r'^dol/(?P<id>\d+)$', views.dol_form),
    (r'^student_meeting/$', views.student_meeting),
    (r'^company_contract/(?P<id>\d+)/$', views.company_contract1),
    (r'^company_contract2/(?P<id>\d+)/$', views.company_contract2),
    (r'^company_contract3/(?P<id>\d+)/$', views.company_contract3),
    (r'^company_contract_complete/(?P<id>\d+)/$', views.company_contract_complete),
    (r'^company_contract_pdf/(?P<id>\d+)/$', views.company_contract_pdf),
    (r'^fte_chart/$', views.fte_chart),
    (r'^routes/$', views.routes),
    (r'^take_attendance/$', views.take_attendance),
    (r'^take_attendance/(?P<work_day>\d+)/$', views.take_attendance),
)

ecwsp/work_study/forms.py
#       forms.py
#       
#       Copyright 2010 Cristo Rey New York High School
#        Author David M Burke <david@burkesoftware.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
from ecwsp.work_study.models import *
from ecwsp.administration.models import *
from ecwsp.sis.forms import StudentReportWriterForm

from django import forms
from django.contrib.admin import widgets as adminwidgets
from django.contrib.localflavor.us.forms import *
from django.utils.safestring import mark_safe
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape

from django.conf import settings

from decimal import Decimal
from datetime import datetime, date
from ajax_select.fields import AutoCompleteSelectMultipleField
from itertools import chain

class StudentForm(forms.ModelForm):
    class Meta:
        model = StudentWorker
    
    ssn = USSocialSecurityNumberField(required=False)
    state = USStateField(required=False)
    zip = USZipCodeField(required=False)
    emergency_contacts = AutoCompleteSelectMultipleField('emergency_contact', required=False)


class CustomCheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    items_per_row = 2 # Number of items per row
    
    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)
        output = ['<table  style="width:99%;"><tr>']
        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])
        for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
            # If an ID attribute was given, add a numeric index as a suffix,
            # so that the checkboxes don't all have the same ID attribute.
            if has_id:
                final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
                label_for = ' for="%s"' % final_attrs['id']
            else:
                label_for = ''
    
            cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_unicode(option_value)
            rendered_cb = cb.render(name, option_value)
            option_label = conditional_escape(force_unicode(option_label))
            if i != 0 and i % self.items_per_row == 0:
                output.append('</tr><tr>')
            output.append('<td nowrap><label%s>%s %s</label></td>' % (label_for, rendered_cb, option_label))
        output.append('</tr></table>')
        return mark_safe('\n'.join(output))



class HorizRadioRenderer(forms.RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
        """Outputs radios"""
        return mark_safe(u'\n'.join([u' %s&nbsp;&nbsp; \n ' % w for w in self]))


class TdRadioRenderer(forms.RadioSelect.renderer):
    """ 
    this overrides widget method to put radio buttons in td's
    """
    def render(self):
        """Outputs radios"""
        #return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))
        return mark_safe(u'\n'.join([u'<td class="border " style="padding"> %s </td>\n' % w for w in self]))

class TdNoTextRadioRenderer(forms.RadioSelect.renderer):
    """ 
    this overrides widget method to put radio buttons in td's
    """
    def render(self):
        """Outputs radios"""
        #return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))
        return mark_safe(u'\n'.join([u'<td class="none nofont" style="font-size: 0px !important; padding-left:10px; padding-right:10px;"> <span style="font-size: 0px;">%s</span> </td>\n' % w for w in self]))


class MapImageWidget(forms.CheckboxInput):
    def render(self, name, value, attrs=None):
        output = []
        output.append(super(MapImageWidget, self).render(name, value, attrs))
        output.append("If checked, the above map file will be overwritten with Google Maps. <table><tr><td><a href=\"javascript:get_map()\">Preview Google Maps</a></td></tr><tr><td> <img width=\"400px\" height=\"400px\" name=\"mapframe\"></iframe> </td></tr></table>")
        return mark_safe(u''.join(output))
        
            
class TimeSheetForm(forms.ModelForm):
    class Meta:
        model = TimeSheet

    my_supervisor = forms.ModelChoiceField(queryset=Contact.objects.all(), required=False)
    date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, validators=settings.DATE_VALIDATORS) 
    time_in = forms.TimeField(widget=forms.TextInput(attrs={'class': 'timecard-datefield'}))
    time_lunch = forms.TimeField(widget=forms.TextInput(attrs={'class': 'timecard-datefield'}))
    time_lunch_return = forms.TimeField(widget=forms.TextInput(attrs={'class': 'timecard-datefield'}))
    time_out = forms.TimeField(widget=forms.TextInput(attrs={'class': 'timecard-datefield'}))
    performance = forms.ModelChoiceField(queryset=TimeSheetPerformanceChoice.objects.all(),required=False,widget=forms.Select(attrs={'class':'timecard-performance'}))
    edit = forms.BooleanField(required=False)

    def set_supers(self, qs):
        self.fields["my_supervisor"].queryset = qs
        
    def clean(self):
        cleaned_data = self.cleaned_data
        time_in = cleaned_data.get("time_in")
        time_lunch = cleaned_data.get("time_lunch")
        time_lunch_return = cleaned_data.get("time_lunch_return")
        time_out = cleaned_data.get("time_out")
        
        # validate max hours
        try:
            hours = time_lunch.hour - time_in.hour
            mins = time_lunch.minute - time_in.minute
            hours += time_out.hour - time_lunch_return.hour
            mins += time_out.minute - time_lunch_return.minute
            hours += mins/Decimal(60)
        except:
            raise forms.ValidationError("You must fill out time in and time out.")
        if hours > settings.MAX_HOURS_DAY:
            raise forms.ValidationError("Only " + unicode(settings.MAX_HOURS_DAY) + " hours are allowed in one day.")
        elif hours <= 0:
            raise forms.ValidationError("You cannot have negative hours!")
            
        
        # validate time in and out
        if time_lunch_return < time_lunch:
            raise forms.ValidationError("Cannot return from lunch before leaving for lunch.")
        if time_in > time_out:
            raise forms.ValidationError("Cannot leave before starting. Check your times.")
        
        #Don't allow two in the same day.
        ts = TimeSheet.objects.filter(date=cleaned_data.get('date'), student=cleaned_data.get('student'))
        
        if ts.count() > 0 and not cleaned_data.get('edit'):
            conf, created = Configuration.objects.get_or_create(name="Allow multiple time sheets in one day")
            if created:
                conf.help_text = "True\nFalse"
                conf.save()
            if conf.value == "False":
                txt = "Cannot submit two time sheets in one day.\n Please edit an existings time sheet if you've" + \
                    " made a mistake. Approved time sheets may only be edited by a supervisor or cwsp staff."
                raise forms.ValidationError(txt)
        # Always return the full collection of cleaned data.
        return cleaned_data

class ChangeSupervisorForm(forms.ModelForm):    
    class Meta:
        model = StudentWorker
        fields = ('primary_contact',)
        
    def __init__(self, *args, **kwargs):
        comp = kwargs.pop('company')
        super(ChangeSupervisorForm, self).__init__(*args, **kwargs)
        self.fields["primary_contact"].queryset = Contact.objects.filter(workteam=comp)

class WorkTeamForm(forms.ModelForm):
    class Meta:
        model = WorkTeam
    
    use_google_maps = forms.BooleanField(required=False, widget=MapImageWidget)
        
class AddSupervisor(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('fname', 'lname', 'phone', 'phone_cell', 'email',)
    
class ReportBuilderForm(forms.Form):
    custom_billing_begin = forms.DateField(widget=adminwidgets.AdminDateWidget(), required=False, validators=settings.DATE_VALIDATORS)
    custom_billing_end = forms.DateField(widget=adminwidgets.AdminDateWidget(), required=False, validators=settings.DATE_VALIDATORS)

class ReportTemplateForm(StudentReportWriterForm):
    date_begin = None
    date_end = None
    student = AutoCompleteSelectMultipleField('studentworker', required=False)
    
    def clean(self):
        data = self.cleaned_data
        if not data.get('student') and not data.get('all_students'):
            raise forms.ValidationError("You must either check \"all students\" or select a student")
        if not data.get('template') and not data.get('upload_template'):
            raise forms.ValidationError("You must either select a template or upload one.")
        return data

class DolForm(forms.ModelForm):
    class Meta:
        model = ClientVisit
        widgets = {
            'date': adminwidgets.AdminDateWidget(),
            'work_environment': forms.RadioSelect(renderer=HorizRadioRenderer),
            'attendance_and_punctuality': forms.RadioSelect(renderer=TdNoTextRadioRenderer),

ecwsp/work_study/templates/work_study/company_contract3.html
{% extends "base.html" %}

{% block css %}
	textarea {
		width:100%;
		height:70px;
	}
	input[type=text] {
		width:300px;
	}
{% endblock %}

{% block content %}
	<h1 style="text-align:center;"> Contract for {{ company }} </h1>
	<br/>
	<div class="contract">
		<form action="" method="post">
			Please review the contract <a href="/work_study/company_contract_pdf/{{ contract.id }}">here</a>. <br/> After checking "I Agree" and hitting next, the contract will be electronically signed. You will be able to print the final version on the next screen. If you need to make changes, you may hit "back", start again, or contact {{ contact_info }}
			<br/><br/>{{ form.as_p }}<br/>
			<input type="submit" value="Next" style="width:150px;"/>
		</form>
	</div>
{% endblock %}

ecwsp/work_study/templates/work_study/company_contract_complete.html
{% extends "base.html" %}

{% block css %}
	textarea {
		width:100%;
		height:70px;
	}
	input[type=text] {
		width:300px;
	}
{% endblock %}

{% block content %}
	<h1 style="text-align:center;"> Contract for {{ company }} </h1>
	<br/>
	<div class="contract">
		Contract accepted. You may download a copy of it <a href="/work_study/company_contract_pdf/{{ contract.id }}">here</a>.
	</div>
{% endblock %}

ecwsp/work_study/templates/work_study/download.html
{% extends "faculty.html" %}

{% block head %}
	<meta http-equiv="Refresh" content="1;url=/files/{{ file }}"/>
	<script type="text/javascript">
		function goBack()
		{
			window.history.back()
		}
	</script>
{% endblock %}

{% block content %}
	The download should start automatically.  If not click <a href="/media/{{ file }}">Here</a>
    <br/>
    <input type="button" value="Back" onclick="goBack()" />
{% endblock %}

ecwsp/work_study/templates/work_study/student_timesheet.html
{% extends "base.html" %}

{% block head %}
    <script type="text/javascript" src="/static/js/jquery.datepicker.min.js"></script>
    
    <script type="text/javascript" src="/static/js/jquery.ptTimeSelect.js"></script>    
    <script type="text/javascript" src="/static/js/date.js"></script>

    <link rel="stylesheet" type="text/css" href="/static/css/jquery-ui-1.7.3.custom.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/css/ui.core.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/css/ui.theme.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.ptTimeSelect.css">
    
    <script type="text/javascript">
    // Wow dates in javascript are soooooo bad
        function add_hours(){
            try {
                var time_in = Date.parse($('#id_time_in').val())
                var hours_in = time_in.getHours();
                var minutes_in = time_in.getMinutes();
                
                var time_out = Date.parse($('#id_time_out').val())
                var hours_out = time_out.getHours();
                var minutes_out = time_out.getMinutes();
                
                var time_lunch = Date.parse($('#id_time_lunch').val())
                var time_lunch_return = Date.parse($('#id_time_lunch_return').val())
                if (time_lunch && time_lunch_return) {
                    var hours_lunch = time_lunch.getHours();
                    var minutes_lunch = time_lunch.getMinutes();
                    var hours_lunch_return = time_lunch_return.getHours();
                    var minutes_lunch_return = time_lunch_return.getMinutes();
                } else {
                    var hours_lunch = 0;
                    var minutes_lunch = 0;
                    var hours_lunch_return = 0;
                    var minutes_lunch_return = 0;
                }
                
                var hours = hours_lunch - hours_in;
                hours = hours + (hours_out - hours_lunch_return);
                
                var minutes = minutes_lunch - minutes_in;
                minutes = minutes + (minutes_out - minutes_lunch_return);
                
                hours = hours + minutes/60;
                hours = Math.round(hours * 100) / 100
                
                $('#span_hours').html(hours);
            } catch (err) {
                $('#span_hours').html("N/A");
            }
            
        }
        
        $(document).ready(
            function () {
                $('code').each(
                    function() {
                        eval($(this).html());
                    }
                )
                add_hours();
                $('#ptTimeSelectSetButton').click(function() {
                    add_hours();
                });
                $('#id_time_in').change(function() {
                    add_hours();
                });
                $('#id_time_out').change(function() {
                    add_hours();
                });
                $('#id_time_lunch').change(function() {
                    add_hours();
                });
                $('#id_time_lunch_return').change(function() {
                    add_hours();
                });
                $(".datepicker").datepicker();
            }
        );
        
        function check_time() {
            lunch_out = document.timesheet_form.time_lunch.value;
            lunch_in = document.timesheet_form.time_lunch_return.value;
            if (lunch_out == "" && lunch_in == "") {
                document.timesheet_form.time_lunch.value = "12:00 pm";
                document.timesheet_form.time_lunch_return.value = "12:00 pm";
            }
            return check_date();
        }
        
        function no_lunch() {
            document.timesheet_form.time_lunch.value = "";
            document.timesheet_form.time_lunch_return.value = "";
            add_hours();
        }
        
        function check_date() {
            date = new Date(document.timesheet_form.date.value.replace('-', '/').replace('-', '/'));
            if (date.getDay()%6==0) {
                if (confirm('Warning: You have selected a weekend.')) {
                    return true;
                } else {
                    return false;
                } 
            }
            return true;
        }
    </script>
{% endblock %}

{% block content %}
<div class="clear"></div>

<div id="pagewrap">


<h1>Create Time Card</h1>

<div class="subhead-text">
You are logged in as
<strong>
    {% if user.first_name and user.last_name %}
        {{ user.first_name }} {{ user.last_name }}
    {% else %}
        {{ user }}
    {% endif %}
</strong>
.
{% if student %}
    Please fill out your time card below.
{% else %}
    Please review {{ studentName.fname }} {{ studentName.lname }}'s time card below.
{% endif %}
</div>

{{ form.non_field_errors }}
{% if warning %}
    <br/><h3 style="color: red;">Warning student has already posted a time sheet for today. You may approve it <a href="{% url "ecwsp.work_study.views.approve" %}?key={{ key }}">here</a></h3><br/>
{% endif %}

<form method="post" name="timesheet_form" onsubmit="return check_time()" action="">

<table class="timecard-date">
<tbody>
    <tr>
        <td>Date</td>
    </tr>
    <tr>
        <td>
            <input
                   type="text"
                   class="timecard-datefield datepicker"
                   name="{{ form.date.html_name }}"
                   id="id_{{ form.date.html_name }}"
                   value="{{ form.date.value }}"/>
        </td>
        {{ form.date.errors }}
    </tr>
</tbody>
</table>

<table class="timecard-date">
<tbody>
	<tr>
		<td>Start</td>
		<td>Lunch Out</td>
		<td>Lunch In</td>
		<td>End</td>
		<td></td>
	</tr>
	<tr>
		<td>{{ form.time_in }} {{ form.time_in.errors }}</td>
		<td>{{ form.time_lunch }} {{ form.time_lunch.errors }}</td>
		<td>{{ form.time_lunch_return }} {{ form.time_lunch_return.errors }}</td>
		<td>{{ form.time_out }} {{ form.time_out.errors }}</td>
		<td><a href="#" onclick="no_lunch()" class="button gray">No Lunch</a></td>
                            <script>
                                $('#id_time_in').ptTimeSelect();
                                $('#id_time_lunch').ptTimeSelect();
                                $('#id_time_lunch_return').ptTimeSelect();
                                $('#id_time_out').ptTimeSelect();
                            </script>
	</tr>
</tbody>
</table>

<div class="subhead-text">
{% if student %} You {% else %} {{ studentName.fname }} {{ studentName.lname }} {% endif %} worked <strong><span id="span_hours"></span></strong> total hours.
</div>


<div class="timecard-comments">
<p>
    {% if student %} My supervisor was: {% else %} Supervisor: {% endif %}
		{{ form.my_supervisor }} {{ form.my_supervisor.errors }}
</p>
</div>


<div class="spacer-3"></div>


<div class="timecard-options">
{% if not form.for_pay.is_hidden %}
    <input type="checkbox" name="{{ form.for_pay.html_name }}" id="id_{{ form.for_pay.html_name }}" {% if form.for_pay.value %}checked="checked"{% endif %}>
        {% if student %} I {% else %} Student {% endif %}was working over a school break (such as a holiday) and should be paid separately for these hours.
    </label><br />
    {{ form.for_pay.errors }} 
{% endif %}
<input type="checkbox" name="{{ form.make_up.html_name }}" id="id_{{ form.make_up.html_name }}" {% if form.make_up.value %}checked="checked"{% endif %}>
    {% if student %} I {% else %} Student {% endif %} was making up a missed day.
</label>
</div>

<div class="spacer-3"></div>

<div class="timecard-comments">

	<p>{% if student %} My {% else %} Student's {% endif %} major accomplishment for today was...</p>
        <textarea
                  class="timecard-commentsbox"
                  id="id_{{ form.student_accomplishment.html_name }}"
                  name="{{ form.student_accomplishment.html_name }}">{{ form.student_accomplishment.value|default_if_none:"" }}</textarea>
        {{ form.student_accomplishment.errors }} 
	
	<p>Client comments, concerns, questions...</p>
        {% if student %}
            <textarea class="timecard-commentsbox" disabled="disabled"></textarea>
        {% else %}
            <textarea
                    class="timecard-commentsbox"
                    id="id_{{ form.supervisor_comment.html_name }}"
                    name="{{ form.supervisor_comment.html_name }}">{{ form.supervisor_comment.value|default_if_none:"" }}</textarea>
            {{ form.supervisor_comment.errors }}
            <br/>
            {{ form.show_student_comments }} Allow students to see comments and performance review.
        {% endif %}

	<p>Daily Student Worker Performance:
		 {{ form.performance.errors }} {{ form.performance }} 
	</p>

{% if approved %}
    <p> Approved by supervisor </p>
{% endif %}    
{% if not student %}
    <p> Submitted by student </p>
{% endif %}
</div>




<div class="spacer-3"></div>


<div class="submitwrap">
{% if student %}
    <input type="submit" class="button gray" value="Submit for Approval">
{% else %}
    <input type="submit" class="button gray" value="Approve Time Card"/>
{% endif %}
<span class="hidden">{{ form.student }} {{ form.company }} {{ form.edit }}</span>
</div>
</form>
{% endblock %}